### ISSUE TITLE
Passing the post ID

### ISSUE THREAD

**Issue by Kpudlo** [stevehenty/gravityformsbutton#1]
Hello Steve, 

Love the plugin! I do have one question, is there a way to pass the current post ID so that I can grab it in a filter? 

Currently when I do the following code, I get a return of nothing because the active post is just the form instead of the page that the post is currently on
```php
add_filter( 'gform_field_value_postid', 'populate_postid' );
function populate_postid( $value ) {
    global $post;
    return $post->ID;
}
```
I went ahead and checked what type of URL the form was returning using `{embed_url}` and it returned this: `example.com/wp-admin/admin-ajax.php?action=gf_button_get_form&form_id=11`

**Comment by stevehenty** [comment]
Sorry for the delay, I've only just seen this. You should be able to use WordPress function `get_the_ID()` and add it to the ajax URL that's output by the shortcode.
